In [73]:
from ultralytics import YOLO
import cv2
import pandas as pd
import re


In [6]:
model=YOLO('best.pt')

In [35]:
import skvideo.io  
videodata = skvideo.io.vread("1.mp4")  
print(videodata.shape)

AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).

In [47]:
vid=list()
cap=cv2.VideoCapture('1.mp4')
while True:
    ret, frame = cap.read()
    if not ret: break # break if no next frame
    
    vid.append(frame) # show frame
    
    if cv2.waitKey(1) & 0xFF == ord('q'): # on press of q break
        break
        
# release and destroy windows
cap.release()
cv2.destroyAllWindows()

In [50]:
results=model(vid)


0: 736x1280 1 BT, 1: 736x1280 1 BT, 2: 736x1280 1 BT, 3: 736x1280 1 BT, 4: 736x1280 1 BT, 5: 736x1280 1 BT, 6: 736x1280 1 BT, 7: 736x1280 1 BT, 8: 736x1280 1 BT, 9: 736x1280 1 BT, 10: 736x1280 1 BT, 11: 736x1280 1 BT, 12: 736x1280 2 BTs, 13: 736x1280 1 BT, 14: 736x1280 2 BTs, 15: 736x1280 1 BT, 16: 736x1280 1 BT, 17: 736x1280 1 BT, 18: 736x1280 2 BTs, 1 Ball, 19: 736x1280 1 BT, 1 Ball, 20: 736x1280 1 BT, 1 Ball, 21: 736x1280 1 BT, 1 Ball, 22: 736x1280 1 BT, 1 Ball, 23: 736x1280 1 BT, 1 Ball, 24: 736x1280 1 BT, 1 Ball, 25: 736x1280 1 BT, 1 Ball, 26: 736x1280 1 BT, 1 Ball, 27: 736x1280 1 BT, 1 Ball, 28: 736x1280 1 BT, 1 Ball, 29: 736x1280 1 BT, 30: 736x1280 1 BT, 1 Ball, 31: 736x1280 1 BT, 1 Ball, 32: 736x1280 1 BT, 1 Ball, 33: 736x1280 2 BTs, 1 Ball, 34: 736x1280 1 BT, 17000.0ms
Speed: 6.5ms preprocess, 485.7ms inference, 1.9ms postprocess per image at shape (1, 3, 1280, 1280)


In [53]:
boxes=list()
for result in results:
    print(result.boxes)
    # masks = result.masks  # Masks object for segmenation masks outputs
    # probs = result.probs  # Class probabilities for classification outputs

tensor([[9.04000e+02, 2.67000e+02, 9.53000e+02, 3.07000e+02, 6.06087e-01, 0.00000e+00]])
tensor([[9.02000e+02, 2.65000e+02, 9.53000e+02, 3.08000e+02, 6.17862e-01, 0.00000e+00]])
tensor([[9.00000e+02, 2.63000e+02, 9.51000e+02, 3.09000e+02, 6.05629e-01, 0.00000e+00]])
tensor([[8.99000e+02, 2.60000e+02, 9.50000e+02, 3.11000e+02, 5.97078e-01, 0.00000e+00]])
tensor([[8.97000e+02, 2.57000e+02, 9.47000e+02, 3.07000e+02, 6.14483e-01, 0.00000e+00]])
tensor([[8.97000e+02, 2.54000e+02, 9.45000e+02, 3.11000e+02, 6.24955e-01, 0.00000e+00]])
tensor([[8.95000e+02, 2.48000e+02, 9.44000e+02, 3.10000e+02, 6.42834e-01, 0.00000e+00]])
tensor([[8.93000e+02, 2.42000e+02, 9.43000e+02, 3.10000e+02, 6.44639e-01, 0.00000e+00]])
tensor([[8.92000e+02, 2.37000e+02, 9.41000e+02, 3.06000e+02, 6.25547e-01, 0.00000e+00]])
tensor([[8.92000e+02, 2.34000e+02, 9.41000e+02, 3.05000e+02, 6.30106e-01, 0.00000e+00]])
tensor([[8.90000e+02, 2.31000e+02, 9.37000e+02, 2.94000e+02, 5.95783e-01, 0.00000e+00]])
tensor([[8.89000e+02,

In [61]:
len(results)

35

In [62]:
len(vid)

35

In [130]:
res=list()
df=pd.DataFrame(columns=["Frame","Class","Confidence","X","Y"])
for result in results:
    for box in result.boxes:
        xyxy=box.xyxy.numpy()[0]
        X=(xyxy[2]-xyxy[0])/2
        Y=(xyxy[3]-xyxy[1])/2
        frame_number=re.search('(?<=image)\d+',result.path).group()
        df.loc[len(df)]=[frame_number,"BAT" if box.cls==0 else "BALL",int(float(box.conf)*100),X,Y]

In [104]:
results[0].boxes[0].xyxy.numpy()

array([[        904,         267,         953,         307]], dtype=float32)

In [134]:
df

Frame Class  Confidence     X      Y
0      0   BAT          60  24.5   20.0
1      1   BAT          61  25.5   21.5
2      2   BAT          60  25.5   23.0
3      3   BAT          59  25.5   25.5
4      4   BAT          61  25.0   25.0
5      5   BAT          62  24.0   28.5
6      6   BAT          64  24.5   31.0
7      7   BAT          64  25.0   34.0
8      8   BAT          62  24.5   34.5
9      9   BAT          63  24.5   35.5
10    10   BAT          59  23.5   31.5
11    11   BAT          57  24.0   32.0
12    12   BAT          61  26.0   37.0
13    12   BAT          28  23.0   29.0
14    13   BAT          58  24.0   29.5
15    14   BAT          56  26.5   35.0
16    14   BAT          43  24.0   27.0
17    15   BAT          60  28.0   28.5
18    16   BAT          59  31.0   24.5
19    17   BAT          58  31.0   19.5
20    18  BALL          84   6.0    7.0
21    18   BAT          55  25.5   10.5
22    18   BAT          39  27.5   12.0
23    19  BALL          85   6.5    7.0
24    19   BAT          52  22.5    9.0
25    20  BALL          88   6.5    7.5
26    20   BAT          55  30.5   14.0
27    21  BALL          75   7.5    8.0
28    21   BAT          71  37.0   33.5
29    22  BALL          88   7.0    8.0
30    22   BAT          78  37.5   49.5
31    23  BALL          81   8.0    8.5
32    23   BAT          78  35.5   65.5
33    24  BALL          86   8.0    8.5
34    24   BAT          81  32.0   74.0
35    25  BALL          86   8.0    8.0
36    25   BAT          82  32.0   79.0
37    26   BAT          83  35.0   72.0
38    26  BALL          81   9.0    9.0
39    27   BAT          86  49.5   44.5
40    27  BALL          44   9.0    8.5
41    28  BALL          88  10.0   10.5
42    28   BAT          75  38.5   37.0
43    29   BAT          86  31.0  102.5
44    30  BALL          85  13.0   12.0
45    30   BAT          69  15.0  101.5
46    31  BALL          80  12.5   12.0
47    31   BAT          78  20.0   53.5
48    32  BALL          85  17.0   16.0
49    32   BAT          42  31.0   54.5
50    33  BALL          85  14.0   14.0
51    33   BAT          83  34.0  118.0
52    33   BAT          27  26.5   90.5
53    34   BAT          84  33.0  126.5

In [136]:
ball=df.loc[df["Class"]=="BALL"]

In [141]:
import matplotlib.pyplot as plt
plt.scatter(ball["X"],ball["Y"])
plt.show()

C:\Users\alira\AppData\Local\Temp\ipykernel_19700\2721814679.py:3: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()


In [139]:
import re
str="image12"
i=re.search('(?<=image)\d+',str).group()
print(int(i))



12
